const pictures = {
    Shawn: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_ShawnA.png",
    Adam: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_AdamR.png",
    Shane: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_ShaneC.png",
    JJ: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_JJB.png",
    Lex: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_LexH.png",
    Kris: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_KrisP.png",
    Chase: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_ChaseW.png",
    Jason: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_JasonH.png",
    Emily: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_EmilyJ.png",
    Brigg: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_BriggA.png",
    Alyssa: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_AlyssaC.png",
    Kelly: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_KellyH.png",
    Jordan: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_JordanH.png",
    Nate: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_NateB.png",
    Matt: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_MattM.png",
    Elitia: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_ElitiaB.png",
    Josh: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_JoshM.png",
    Colby: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_ColbyB.png",
    Victoria: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_VictoriaB.png",
    Rene: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_ReneD.png",
    Chris: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_ChrisJ.png",
    Katie: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_KatieS.png",
    JakeH: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_JakeH.png",
    Lisa: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_LisaD.png",
    MarkW: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_MarkW.png",
    Alex: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_AlexM.png",
    Mark: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_MarkH.png",
    JasonM: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_JasonN.png",
    Steven: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_StevenV.png",
    Stephanie: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_StephanieW.png",
    Julie: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_JulieO.png",
    Jake: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_JakeM.png",
    Brett: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_BrettG.png",
    StevenS: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_StevenS.png",
    Whitney: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_WhitneyS.png",
    Shelby: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_ShelbyT.png",
    Dakota: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_DakotaC.png",
    Lauren: "https://cdn.pdq.com/wp-content/uploads/2018/08/company_LaurenC.png",
    Jon: "https://cdn.pdq.com/wp-content/uploads/2018/08/Jon2.png",
    JoshA: "https://cdn.pdq.com/wp-content/uploads/2018/09/company_JoshA.png",
    Sergio: "https://cdn.pdq.com/wp-content/uploads/2018/09/company_SergioD.png",
    Michael: "https://cdn.pdq.com/wp-content/uploads/2018/12/company_MichaelB.png",
    Greg: "https://cdn.pdq.com/wp-content/uploads/2019/02/company_GregS.png",
    Dani: "https://cdn.pdq.com/wp-content/uploads/2019/04/DaniW.png",
    Brook: "https://cdn.pdq.com/wp-content/uploads/2019/04/BrookA.png",
    Randall: "https://cdn.pdq.com/wp-content/uploads/2019/04/RandalP.png",
    Renzo: "https://cdn.pdq.com/wp-content/uploads/2019/04/RenzoT.png",
    Paul: "https://cdn.pdq.com/wp-content/uploads/2019/04/PaulS.png",
    Jarem: "https://cdn.pdq.com/wp-content/uploads/2019/05/company_Jarom.png",
    Bryan: "https://cdn.pdq.com/wp-content/uploads/2019/05/company_BryaM.png"
}


export default pictures;